#' Select scale scores
#' Selects a data frame with score variables generated by score_scale.
#'
#' @param data A data frame
#' @return A data frame
#' @export
select_scores <- function(data) {
  filter <- which(
    sapply(
      data, function(x) dic_attr(x, .opt$class) == "score"
    )
  )

  data[, filter, drop = FALSE]
}
